"""
This type stub file was generated by pyright.
"""

class StateStorageBase:
    def __init__(self) -> None:
        ...
    
    async def set_data(self, chat_id, user_id, key, value):
        """
        Set data for a user in a particular chat.
        """
        ...
    
    async def get_data(self, chat_id, user_id):
        """
        Get data for a user in a particular chat.
        """
        ...
    
    async def set_state(self, chat_id, user_id, state):
        """
        Set state for a particular user.

        ! Note that you should create a 
        record if it does not exist, and 
        if a record with state already exists,
        you need to update a record.
        """
        ...
    
    async def delete_state(self, chat_id, user_id):
        """
        Delete state for a particular user.
        """
        ...
    
    async def reset_data(self, chat_id, user_id):
        """
        Reset data for a particular user in a chat.
        """
        ...
    
    async def get_state(self, chat_id, user_id):
        ...
    
    async def save(self, chat_id, user_id, data):
        ...
    


class StateContext:
    """
    Class for data.
    """
    def __init__(self, obj, chat_id, user_id) -> None:
        ...
    
    async def __aenter__(self):
        ...
    
    async def __aexit__(self, exc_type, exc_val, exc_tb):
        ...
    


