"""
This type stub file was generated by pyright.
"""

from telebot.asyncio_storage.base_storage import StateStorageBase

class StatePickleStorage(StateStorageBase):
    def __init__(self, file_path=...) -> None:
        ...
    
    async def convert_old_to_new(self): # -> None:
        ...
    
    def create_dir(self): # -> None:
        """
        Create directory .save-handlers.
        """
        ...
    
    def read(self): # -> Any:
        ...
    
    def update_data(self): # -> None:
        ...
    
    async def set_state(self, chat_id, user_id, state): # -> Literal[True]:
        ...
    
    async def delete_state(self, chat_id, user_id): # -> bool:
        ...
    
    async def get_state(self, chat_id, user_id): # -> Any | None:
        ...
    
    async def get_data(self, chat_id, user_id): # -> Any | None:
        ...
    
    async def reset_data(self, chat_id, user_id): # -> bool:
        ...
    
    async def set_data(self, chat_id, user_id, key, value): # -> Literal[True]:
        ...
    
    def get_interactive_data(self, chat_id, user_id): # -> StateContext:
        ...
    
    async def save(self, chat_id, user_id, data): # -> None:
        ...
    


