"""
This type stub file was generated by pyright.
"""

class BaseMiddleware:
    """
    Base class for middleware.
    Your middlewares should be inherited from this class.
    """
    def __init__(self) -> None:
        ...
    
    async def pre_process(self, message, data):
        ...
    
    async def post_process(self, message, data, exception):
        ...
    


class State:
    def __init__(self) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class StatesGroup:
    def __init_subclass__(cls) -> None:
        ...
    


class SkipHandler:
    """
    Class for skipping handlers.
    Just return instance of this class 
    in middleware to skip handler.
    Update will go to post_process,
    but will skip execution of handler.
    """
    def __init__(self) -> None:
        ...
    


class CancelUpdate:
    """
    Class for canceling updates.
    Just return instance of this class 
    in middleware to skip update.
    Update will skip handler and execution
    of post_process in middlewares.
    """
    def __init__(self) -> None:
        ...
    


